config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  devise_for :artists
  resources :artists, except: [:new, :create, :destroy] do
  	member do
  		get "my_profile" => "artists#my_profile", as: :my_profile
  	end
  end
  resources :owners, except: [:new, :create, :destroy]
  resources :blank_walls
  get 'home/index'
  get "sign_in" => "home#sign_in", as: :sign_in
  root 'home#index'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
	mount_uploader :avatar, AvatarUploader
	mount_uploader :portafolio_1, PortafolioUploader
	mount_uploader :portafolio_2, PortafolioUploader
	mount_uploader :portafolio_3, PortafolioUploader
	validates :email, presence: true
	after_validation :set_verifications, on: [ :create, :update ]
	scope :have_specifed_rate, -> { where("min_rate is not null and max_rate is not null") }
	scope :with_payment_between, ->(max_value, min_value) { where("min_rate <= :min_value and max_rate >= :max_value", {min_value: min_value, max_value: max_value}) }
	def avatar_picture
		self.avatar.url.blank? ? "default-avatar.png" : self.avatar.url
	end

	def email_confirmed?
		!self.confirmed_at.nil?
	end

	def set_verifications
		self.phone_verified = !self.phone_number.blank?
		self.profile_completed = self.email_confirmed? and (!self.twitter.blank? or !self.facebook.blank?) and (!self.nickname.blank? or !self.name.blank?) and !self.portafolio_1.blank? and !self.avatar.blank? self.have_specifed_rate? 
	end

	def artist_identifier
		if self.name.present?
			self.name
		elsif self.nickname.present?
			self.nickname
		else
			self.email.split("@")[0]
		end
	end

	def phone_confirmed?
		self.phone_verified
	end

	def profile_completed?
		self.profile_completed
	end

	def have_specifed_rate?
		!self.min_rate.nil? and !self.max_rate.nil?
	end

	def rate_range
		"#{self.min_rate},#{self.max_rate}"
	end

	def rate_range=(rate_range)
		@rate_range = rate_range
		range = rate_range.split(",")
		self.min_rate = range[0]
		self.max_rate = range[1]
	end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy, :my_profile]
  before_action :authenticate_artist!, only: [:edit, :update]
  before_action :authenticate_owner!, only: [:index, :show]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.have_specifed_rate.where("confirmed_at is not null")
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  def my_profile
    render action: :show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to my_profile_artist_path(id:@artist.id), notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.active = false
    @artist.save
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit!
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @artist.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h4>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nickname, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nickname, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :avatar, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :avatar, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :twitter, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :twitter, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :facebook, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :facebook, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :portafolio_1, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :portafolio_1, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :portafolio_2, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :portafolio_2, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :portafolio_3, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :portafolio_3, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/artists/edit.html.erb
<div class="page-header">
  <%= link_to artists_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @artist, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing artist</h1>
</div>

<%= form_for(@artist, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @artist.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h4>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :avatar, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :avatar, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :nickname, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nickname, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :rate_range, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :rate_range, :class => "form-control", data:{:"slider-min" => 10, :"slider-max" => 1000, :"slider-step"=>10, :"slider-value" => 100, :"slider-value" => "[#{@artist.rate_range}]"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :twitter, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :twitter, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :facebook, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :facebook, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :portafolio_1, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :portafolio_1, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :portafolio_2, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :portafolio_2, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :portafolio_3, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :portafolio_3, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

<%= content_for :javascript_fixes do%>
  <script type="text/javascript">
    $("#artist_rate_range").slider({});
  </script>
<% end %>

app/views/artists/index.html.erb
<div class="page-header">
  <h1>Listing artists</h1>
</div>

<div class="table-responsive">
  <% unless @artists.length > 0 %>
    <h2>No results were Found</h2>
  <% else %>
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
              <th>Artist</th>
              <th>Rate</th>
              <th></th>
              <th></th>
              <th></th>
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @artists) do |artist| %>
          <td><%= link_to artist.artist_identifier, artist_path(id: artist.id) %></td>
          <td>$<%= artist.min_rate %> - $<%= artist.max_rate %></td>

          <td>
            <% unless artist.email_confirmed? %>
              <span class="label label-danger">Email not Confirmed</span>
            <% else %>
              <span class="label label-success">Email Confirmed</span>
            <% end %>
          </td>

          <td>
            <% unless artist.phone_confirmed? %>
              <span class="label label-danger">Phone not Confirmed</span>
            <% else %>
              <span class="label label-success">Phone Confirmed</span>
            <% end %>
          </td>

          <td>
            <% unless artist.profile_completed? %>
              <span class="label label-danger">Profile not Completed</span>
            <% else %>
              <span class="label label-success">Profile Completed</span>
            <% end %>
          </td>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/artists/new.html.erb
<div class="page-header">
  <%= link_to artists_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New artist</h1>
</div>

<%= form_for(@artist, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @artist.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h4>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nickname, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nickname, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :portafolio_1, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :portafolio_1, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :portafolio_2, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :portafolio_2, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :portafolio_3, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :portafolio_3, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/artists/show.html.erb
<div class="page-header">
  <% if artist_signed_in? %>
    <%= link_to artists_path, :class => 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <%= link_to edit_artist_path(@artist), :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit my Profile
    <% end %>
  <% end %>
  <h1>Show artist</h1>
</div>
<%= image_tag @artist.avatar_picture, style: "width: 200px;margin-bottom: 10px;" %>
<dl class="dl-horizontal">
  <dt>Artist:</dt>
  <dd><%= @artist.artist_identifier %></dd>

  <dt>Rate:</dt>
  <dd>$<%= @artist.min_rate %> - $<%= @artist.max_rate %> Ft<sup>2</sup></dd>

  <dt>Email:</dt>
  <dd>
    <% unless @artist.email_confirmed? %>
      <span class="label label-danger">Not Confirmed</span>
    <% else %>
      <span class="label label-success">Confirmed</span>
    <% end %>
  </dd>

  <dt>Phone:</dt>
  <dd>
    <% unless @artist.phone_confirmed? %>
      <span class="label label-danger">Not Confirmed</span>
    <% else %>
      <span class="label label-success">Confirmed</span>
    <% end %>
  </dd>

  <dt>Profile:</dt>
  <dd>
    <% unless @artist.profile_completed? %>
      <span class="label label-danger">Not Completed</span>
    <% else %>
      <span class="label label-success">Completed</span>
    <% end %>
  </dd>

            


<p>
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" >
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag @artist.portafolio_1%>
        <div class="carousel-caption">
        </div>
      </div>
      
      <% unless @artist.portafolio_2.url.blank? %>
        <div class="item">
          <%= image_tag @artist.portafolio_2.url%>
          <div class="carousel-caption">
          </div>
        </div>
      <% end %>

      <% unless @artist.portafolio_3.url.blank? %>
        <div class="item">
          <%= image_tag @artist.portafolio_3.url%>
          <div class="carousel-caption">
          </div>
        </div>
      <% end %>
      </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</p>

</dl>