config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  devise_for :artists
  resources :artists, except: [:new, :create, :destroy] do
  	member do
  		get "my_profile" => "artists#my_profile", as: :my_profile
  	end
  end
  resources :owners, except: [:new, :create, :destroy]
  resources :blank_walls
  get 'home/index'
  get "sign_in" => "home#sign_in", as: :sign_in
  root 'home#index'
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blank_walls

  def nickname
  	if self.name.blank?
  		self.email.split("@")[0]
  	else
  		self.name
  	end
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "fillmywall", password: "jhlive300590/*-+"

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:email, :name)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @owner.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h4>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/owners/edit.html.erb
<div class="page-header">
  <%= link_to owners_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @owner, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing owner</h1>
</div>

<%= render 'form' %>

app/views/owners/index.html.erb
<div class="page-header">
  <%= link_to new_owner_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Owner
  <% end %>
  <h1>Listing owners</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Email</th>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @owners) do |owner| %>
            <td><%= owner.email %></td>
            <td><%= owner.name %></td>
            <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/owners/new.html.erb
<div class="page-header">
  <%= link_to owners_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New owner</h1>
</div>

<%= render 'form' %>

app/views/owners/show.html.erb
<div class="page-header">
  <%= link_to owners_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_owner_path(@owner), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show owner</h1>
</div>

<dl class="dl-horizontal">
  <dt>Email:</dt>
  <dd><%= @owner.email %></dd>

  <dt>Name:</dt>
  <dd><%= @owner.name %></dd>

</dl>