config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  devise_for :artists
  resources :artists, except: [:new, :create, :destroy] do
  	member do
  		get "my_profile" => "artists#my_profile", as: :my_profile
  	end
  end
  resources :owners, except: [:new, :create, :destroy]
  resources :blank_walls
  get 'home/index'
  get "sign_in" => "home#sign_in", as: :sign_in
  root 'home#index'
end

app/models/blank_wall.rb
class BlankWall < ActiveRecord::Base
  belongs_to :owner
	mount_uploader :picture_1, PortafolioUploader
	mount_uploader :picture_2, PortafolioUploader
	mount_uploader :picture_3, PortafolioUploader
	validates :area, :done_by, :budget_range, :min_budget, :max_budget, :picture_1, presence: true
	validates :done_by, format: { with: /\d\d\d\d-\d\d-\d\d/, message: "Wrong date format" }
	#scope :with_payment_between, ->(min_value, max_value) { where("blank_walls.min_budget <= :min_value and blank_walls.max_budget >= :max_value", {min_value: min_value*1.0, max_value: max_value*1.0}) }

	def budget_range
		"#{self.min_budget},#{self.max_budget}"
	end

	def budget_range=(budget_range)
		@budget_range = budget_range
		range = budget_range.split(",")
		self.min_budget = range[0]
		self.max_budget = range[1]
	end

	def self.find_with_filter(filter)
		self.all
	end
end

app/controllers/blank_walls_controller.rb
class BlankWallsController < ApplicationController
  before_action :set_blank_wall, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_owner!, except:[:index, :show]
  before_action :authenticate_user!, only: [:index, :show]

  # GET /blank_walls
  # GET /blank_walls.json
  def index
    @filter = Filter.build_new_filter(params[:filter])
    unless @filter.is_default
      @blank_walls = owner_signed_in? ? current_owner.blank_walls : BlankWall.find_with_filter(@filter)
    else
      @blank_walls = owner_signed_in? ? current_owner.blank_walls : BlankWall.all
    end
  end

  # GET /blank_walls/1
  # GET /blank_walls/1.json
  def show
  end

  # GET /blank_walls/new
  def new
    @blank_wall = BlankWall.new
    @blank_wall.owner_id = current_owner.id
    @blank_wall.min_budget = 100
    @blank_wall.max_budget = 500
    @blank_wall.area = 25
  end

  # GET /blank_walls/1/edit
  def edit
  end

  # POST /blank_walls
  # POST /blank_walls.json
  def create
    @blank_wall = BlankWall.new(blank_wall_params)
    budget_range = blank_wall_params[:budget_range].split(",")
    @blank_wall.min_budget = budget_range[0]
    @blank_wall.max_budget = budget_range[1]
    respond_to do |format|
      if @blank_wall.save
        format.html { redirect_to @blank_wall, notice: 'Blank wall was successfully created.' }
        format.json { render :show, status: :created, location: @blank_wall }
      else
        format.html { render :new }
        format.json { render json: @blank_wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blank_walls/1
  # PATCH/PUT /blank_walls/1.json
  def update
    respond_to do |format|
      if @blank_wall.update(blank_wall_params)
        format.html { redirect_to @blank_wall, notice: 'Blank wall was successfully updated.' }
        format.json { render :show, status: :ok, location: @blank_wall }
      else
        format.html { render :edit }
        format.json { render json: @blank_wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blank_walls/1
  # DELETE /blank_walls/1.json
  def destroy
    @blank_wall.destroy
    respond_to do |format|
      format.html { redirect_to blank_walls_url, notice: 'Blank wall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blank_wall
      @blank_wall = BlankWall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blank_wall_params
      params.require(:blank_wall).permit!
    end
end

app/helpers/blank_walls_helper.rb
module BlankWallsHelper
end

app/views/blank_walls/_form.html.erb
<%= form_for(@blank_wall, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @blank_wall.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@blank_wall.errors.count, "error") %> prohibited this blank_wall from being saved:</h4>

      <ul>
      <% @blank_wall.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :owner_id, :class => "form-control" %>

  <div class="form-group">
    <%= f.label :area, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :area, :class => "form-control", data:{:"slider-min" => 1, :"slider-max" => 100, :"slider-step"=>1, :"slider-value" => 10} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :budget_range, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :budget_range, :class => "form-control", data:{:"slider-min" => 10, :"slider-max" => 1000, :"slider-step"=>10, :"slider-value" => 100, :"slider-value" => "[#{@blank_wall.budget_range}]"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :done_by, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_field :done_by, :class => "form-control" %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :description, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, rows: 3, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :picture_1, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :picture_1, rows: 3, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :picture_2, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :picture_2, rows: 3, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :picture_3, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :picture_3, rows: 3, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

<%= content_for :javascript_fixes do %>
  <script type="text/javascript">
    $("#blank_wall_area").slider({});
    $("#blank_wall_budget_range").slider({});
  </script>
<% end %>

app/views/blank_walls/edit.html.erb
<div class="page-header">
  <%= link_to blank_walls_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @blank_wall, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing blank_wall</h1>
</div>

<%= render 'form' %>

app/views/blank_walls/index.html.erb
<div class="page-header">
  <% if owner_signed_in? %>
    <%= link_to new_blank_wall_path, :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Blank wall
    <% end %>
  <% else %>
    <%= render partial: "partials/wall_filters"%>
  <% end %>
  <h1>Listing blank_walls</h1>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Owner</th>
        <th>Area</th>
        <th>Budget</th>
        <% if owner_signed_in? %>
          <th></th>
          <th></th>       
        <% end %>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @blank_walls) do |blank_wall| %>
        <td><%= link_to blank_wall.owner.nickname, blank_wall %></td>
        <td><%= blank_wall.area %> ft<sup>2</sup></td>
        <td>$<%= blank_wall.min_budget %> - $<%= blank_wall.max_budget %></td>
        <% if owner_signed_in? %>
          <td><%= link_to 'Edit', edit_blank_wall_path(blank_wall) %></td>
          <td><%= link_to 'Destroy', blank_wall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/blank_walls/new.html.erb
<div class="page-header">
  <%= link_to blank_walls_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New blank_wall</h1>
</div>

<%= render 'form' %>

app/views/blank_walls/show.html.erb
<div class="page-header">
<% if owner_signed_in? %>
  <%= link_to blank_walls_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_blank_wall_path(@blank_wall), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
<% else %>
  <%= link_to "#", :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Bid
  <% end %>
<% end %>
  <h1>Show blank_wall</h1>
</div>

<dl class="dl-horizontal">
  <dt>Area:</dt>
  <dd><%= @blank_wall.area %></dd>

  <dt>Budget:</dt>
  <dd><%= @blank_wall.min_budget %>-<%= @blank_wall.max_budget %></dd>

</dl>
<div class = "row">
  <div class = "">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" >
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <%= image_tag @blank_wall.picture_1%>
            <div class="carousel-caption">
            </div>
          </div>
          
          <% unless @blank_wall.picture_2.url.blank? %>
            <div class="item">
              <%= image_tag @blank_wall.picture_2.url%>
              <div class="carousel-caption">
              </div>
            </div>
          <% end %>

          <% unless @blank_wall.picture_3.url.blank? %>
            <div class="item">
              <%= image_tag @blank_wall.picture_3.url%>
              <div class="carousel-caption">
              </div>
            </div>
          <% end %>


          <div class="item">
            <%= image_tag @blank_wall.picture_3%>
            <div class="carousel-caption">
            </div>
          </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
  </div>
</div>