config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  devise_for :artists
  resources :artists, except: [:new, :create, :destroy] do
  	member do
  		get "my_profile" => "artists#my_profile", as: :my_profile
  	end
  end
  resources :owners, except: [:new, :create, :destroy]
  resources :blank_walls
  get 'home/index'
  get "sign_in" => "home#sign_in", as: :sign_in
  root 'home#index'
end

app/views/partials/_landing_carousel.html.erb
<div id="carousel-id" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carousel-id" data-slide-to="0" class=""></li>
        <li data-target="#carousel-id" data-slide-to="1" class=""></li>
        <li data-target="#carousel-id" data-slide-to="2" class="active"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item">
            <%= image_tag "landing1.jpg" %>
            <div class="container">
                <div class="carousel-caption">
                    <h1>Example headline.</h1>
                    <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
                </div>
            </div>
        </div>
        <div class="item">
            <%= image_tag "landing2.jpg" %>
            <div class="container">
                <div class="carousel-caption">
                    <h1>Another example headline.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                </div>
            </div>
        </div>
        <div class="item active">
            <%= image_tag "landing3.jpg" %>
            <div class="container">
                <div class="carousel-caption">
                    <h1>One more for good measure.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#carousel-id" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#carousel-id" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>

app/views/partials/_landing_header.html.erb
<header id = "navbar-header">
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Muralist", root_path, :class => "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <%= render "partials/navbar_options"%>
        <%= render "partials/signin_options"%>
      </div>
    </div>
  </nav>
  <%= render "partials/landing_carousel"  %>
</header>

app/views/partials/_navbar_options.html.erb
<ul class="nav navbar-nav">
  <% if owner_signed_in? %>
    <li><%= link_to "Artist", artists_path %></li>
    <li><%= link_to "My Posted Walls", blank_walls_path %></li>
  <% else %>
    <li><%= link_to "Find a Wall", blank_walls_path %></li>
  <% end %>
</ul>

app/views/partials/_signin_options.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if artist_signed_in? %>
    <li><%= link_to "Sign out (Artist)", destroy_artist_session_path, method: :delete %></li>
    <li><%= link_to "My Profile", my_profile_artist_path(id: current_artist.id) %></li>
  <% elsif owner_signed_in? %>
    <li><%= link_to "Sign out (Owner)", destroy_owner_session_path, method: :delete %></li>  
  <% else %>
    <li><%= link_to "Sign in", sign_in_path %></li>
  <% end %>
</ul>

app/views/partials/_wall_filter.html.erb
<h1>Hello world</h1>

app/views/partials/_wall_filters.html.erb
<h2>Search Wall Post</h2>
<%= form_for @filter, url: blank_walls_path, method: :get, :html => { :class => "form-horizontal", :role => "form" } do |f| -%>
	<div class="form-group">
    <%= f.label :area, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :area, :class => "form-control", data:{:"slider-min" => 1, :"slider-max" => 100, :"slider-step"=>1, :"slider-value" => 10} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :budget_range, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :budget_range, :class => "form-control", data:{:"slider-min" => 10, :"slider-max" => 1000, :"slider-step"=>10, :"slider-value" => 100, :"slider-value" => "[#{@filter.budget_range}]"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :wall_type, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
    	<%= f.select :wall_type, Filter.wall_types, {prompt: "--"}, {:class => "form-control"} %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Find me walls", :class => "btn btn-primary" %>
    </div>
  </div>

<% end %>


<%= content_for :javascript_fixes do %>
  <script type="text/javascript">
    $("#filter_area").slider({});
    $("#filter_budget_range").slider({});
  </script>
<% end %>